Custom_header_links:
  type: list
  list_type: simple
  default: "External link, this link will open in a new tab, https://meta.discourse.org, vdo, blank, remove, up-1|Most Liked, Posts with the most amount of likes, /latest/?order=op_likes, vdo, self, keep, 0|Privacy, Our Privacy Policy, /privacy, vdm, self, keep, down-1"
  description:
    en: "Comma delimited in this order: link text, link title, URL, view, target, hide on scroll, font size<br><b>Link text:</b> The text for the link<br><b>Link title:</b> the text that shows when the link is hovered<br><b>URL:</b> The path for the link (can be relative)<br><b>View:</b> vdm = desktop and mobile, vdo = desktop only, vmo = mobile only<br><b>Target:</b> blank = opens in a new tab, self = opens in the same tab<br><b>Hide on scroll:</b> remove = hides the link when the title is expanded on topic pages keep = keeps the link visible even when the title is visible on topic pages<br><b>Font size:</b> e.g.: up-1, 0, down-1, etc."

links_position:
  default: right
  type: enum
  choices:
    - right
    - left
  description:
    en: "Note that when links are displayed on the left, they're automatically hidden while scrolling within topics to make room for the title"
